<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <AssemblyName>FrpWin</AssemblyName>
    <RootNamespace>FrpWin</RootNamespace>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyTitle>FrpWin 内网穿透管理器</AssemblyTitle>
    <Product>FrpWin</Product>
    <Company>FrpWin</Company>
    <Copyright>Copyright © 2025</Copyright>
    <Version>1.0.0</Version>
    <FileVersion>1.0.0.0</FileVersion>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <Deterministic>true</Deterministic>
    <SatelliteResourceLanguages>zh-Hans;en</SatelliteResourceLanguages>
    <DebugType>none</DebugType>
    <ErrorReport>none</ErrorReport>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <Reference Include="System.ServiceProcess" />
  </ItemGroup>

</Project>
